plugins {
    id "com.android.application"
}

android {
    namespace "com.rootfan.shieldtools"
    compileSdk 35

    defaultConfig {
        applicationId "com.rootfan.shieldtools.overlay"
        minSdk 28
        targetSdk 35
        versionCode 2
        versionName "1.5"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
